// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// set_seed
void set_seed(unsigned int seed);
RcppExport SEXP _phyr_set_seed(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    set_seed(seed);
    return R_NilValue;
END_RCPP
}
// predict_cpp
NumericVector predict_cpp(int n, const arma::vec& nsr, int reps, const arma::mat& V);
RcppExport SEXP _phyr_predict_cpp(SEXP nSEXP, SEXP nsrSEXP, SEXP repsSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nsr(nsrSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_cpp(n, nsr, reps, V));
    return rcpp_result_gen;
END_RCPP
}
// pcd2_loop
List pcd2_loop(arma::vec SSii, arma::vec nsr, double SCii, const arma::mat& comm, const arma::mat& V, int nsp_pool, bool verbose);
RcppExport SEXP _phyr_pcd2_loop(SEXP SSiiSEXP, SEXP nsrSEXP, SEXP SCiiSEXP, SEXP commSEXP, SEXP VSEXP, SEXP nsp_poolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type SSii(SSiiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nsr(nsrSEXP);
    Rcpp::traits::input_parameter< double >::type SCii(SCiiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type comm(commSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type nsp_pool(nsp_poolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(pcd2_loop(SSii, nsr, SCii, comm, V, nsp_pool, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phyr_set_seed", (DL_FUNC) &_phyr_set_seed, 1},
    {"_phyr_predict_cpp", (DL_FUNC) &_phyr_predict_cpp, 4},
    {"_phyr_pcd2_loop", (DL_FUNC) &_phyr_pcd2_loop, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_phyr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
