# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pglmm_reml_cpp <- function(par, tinvW, tH, tVphy, tX) {
    .Call(`_phyr_pglmm_reml_cpp`, par, tinvW, tH, tVphy, tX)
}

binpglmm_inter_while_cpp <- function(est_B_m, oldest_B_m, B, tol_pql, iteration_m, maxit_pql, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b) {
    .Call(`_phyr_binpglmm_inter_while_cpp`, est_B_m, oldest_B_m, B, tol_pql, iteration_m, maxit_pql, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b)
}

binpglmm_inter_while_cpp2 <- function(est_B_m, B, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b) {
    .Call(`_phyr_binpglmm_inter_while_cpp2`, est_B_m, B, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b)
}

#' Inline C++ that does most of the work related to the log-likelihood function.
#' 
#' See below for the `nlopt` and `stats::optim` versions
#' 
#' 
#' @name cor_phylo_LL_
#' @noRd
#' 
#' 
NULL

#' `cor_phylo` log likelihood function for use with `nlopt`.
#' 
#' Note that this function is referred to the "objective function" in the `nlopt`
#' documentation and the input arguments should not be changed.
#' See
#' [here](https://nlopt.readthedocs.io/en/latest/NLopt_Reference/#objective-function)
#' for more information.
#' 
#' @param n the number of optimization parameters
#' @param x an array of length `n` of the optimization parameters
#' @param grad an array that is not used here, but the `nlopt` documentation describes
#'   it as such: "an array of length `n` which should (upon return) be set to the 
#'   gradient of the function with respect to the optimization parameters at `x`."
#' @param f_data pointer to an object with additional information for the function.
#'   In this function's case, it is an object of class `LL_info`.
#' 
#' @return the negative log likelihood
#' 
#' @name cor_phylo_LL
#' @noRd
#' 
NULL

#' Fit cor_phylo model using nlopt.
#'
#'
#' @inheritParams ll_info cp_get_output
#' @inheritParams max_iter cor_phylo
#' @inheritParams method cor_phylo
#' 
#' @return Nothing. `ll_info` is modified in place to have info from the model fit
#'   after this function is run.
#'
#' @name fit_cor_phylo_nlopt
#' @noRd
#' 
NULL

#' Fit `cor_phylo` model using R's `stats::optim`.
#' 
#' Make sure this doesn't get run in parallel!
#'
#'
#' @inheritParams ll_obj_xptr cor_phylo_LL_R
#' @inheritParams max_iter cor_phylo
#' @inheritParams method cor_phylo
#' 
#' @return Nothing. `ll_obj_xptr` is modified in place to have info from the model fit
#'   after this function is run.
#'
#' @name fit_cor_phylo_R
#' @noRd
#' 
NULL

#' Standardize matrices in place.
#' 
#' Makes each column of the `X` matrix have mean of zero and standard deviation of 1.
#' If `U` isn't empty, this function makes each column in each matrix have
#' mean of zero and standard deviation of 1, unless all values are the same, in which
#' case it keeps the standard deviation at zero.
#' Divides each column of `M` by the original standard deviation of that column in 
#' `X`.
#' 
#' 
#' @inheritParams X cor_phylo_
#' @inheritParams U cor_phylo_
#' @inheritParams M cor_phylo_
#' 
#' @return Nothing. Matrices are standardized in place.
#' 
#' @name standardize_matrices
#' @noRd
#' 
NULL

#' Make an `LL_info` object based on input matrices.
#' 
#' This `LL_info` is used for model fitting.
#' 
#' @inheritParams X cor_phylo_
#' @inheritParams U cor_phylo_
#' @inheritParams M cor_phylo_
#' @inheritParams Vphy_ cor_phylo_
#' @inheritParams REML_ cor_phylo_
#' @inheritParams constrain_d_ cor_phylo_
#' @inheritParams verbose_ cor_phylo_
#' 
#' @return a LL_info that contains info necessary for model fitting
#' 
#' @name LL_info
#' @noRd
#' 
NULL

#' Retrieve objects for output `cor_phylo` object.
#' 
#' @inheritParams X cor_phylo_
#' @inheritParams U cor_phylo_
#' @param ll_info an LL_info object that contains info necessary to fit the model.
#'   After optimization, it contains info from the model fit.
#' 
#' @return a list containing output information, to later be coerced to a `cor_phylo`
#'   object by the `cor_phylo` function.
#' 
#' @name cp_get_output
#' @noRd
#' 
NULL

#' `cor_phylo` log likelihood function for R's `stats::optim`.
#' 
#' 
#' @param par Initial values for the parameters to be optimized over.
#' @param ll_obj_xptr `Rcpp::Xptr` object that points to a C++ `LL_info` object.
#'     This object stores all the other information needed for the log likelihood
#'     function.
#' 
#' @noRd
#' 
#' @name cor_phylo_LL_R
#' 
cor_phylo_LL_R <- function(par, ll_obj_xptr) {
    .Call(`_phyr_cor_phylo_LL_R`, par, ll_obj_xptr)
}

#' Inner function to create necessary matrices and do model fitting.
#' 
#' @param X a n x p matrix with p columns containing the values for the n taxa.
#' @param U a list of p matrices corresponding to the p columns of `X`, with each 
#'   matrix containing independent variables for the corresponding column of `X`.
#' @param M a n x p matrix with p columns containing standard errors of the trait 
#'   values in `X`. 
#' @param Vphy_ phylogenetic variance-covariance matrix from the input phylogeny.
#' @inheritParams REML cor_phylo
#' @inheritParams constrain_d cor_phylo
#' @inheritParams verbose cor_phylo
#' @inheritParams max_iter cor_phylo
#' @param method the `method` input to `cor_phylo`, converted to an integer
#'   that indexes which method it should be.
#' 
#' @return a list containing output information, to later be coerced to a `cor_phylo`
#'   object by the `cor_phylo` function.
#' @noRd
#' @name cor_phylo_
#' 
cor_phylo_ <- function(X, U, M, Vphy_, REML, constrain_d, verbose, rel_tol, max_iter, method) {
    .Call(`_phyr_cor_phylo_`, X, U, M, Vphy_, REML, constrain_d, verbose, rel_tol, max_iter, method)
}

set_seed <- function(seed) {
    invisible(.Call(`_phyr_set_seed`, seed))
}

predict_cpp <- function(n, nsr, reps, V) {
    .Call(`_phyr_predict_cpp`, n, nsr, reps, V)
}

pcd2_loop <- function(SSii, nsr, SCii, comm, V, nsp_pool, verbose) {
    .Call(`_phyr_pcd2_loop`, SSii, nsr, SCii, comm, V, nsp_pool, verbose)
}

plmm_binary_iV_logdetV_cpp <- function(par, mu, Zt, St, nested, logdet) {
    .Call(`_phyr_plmm_binary_iV_logdetV_cpp`, par, mu, Zt, St, nested, logdet)
}

plmm_binary_V <- function(par, Zt, St, mu, nested, missing_mu) {
    .Call(`_phyr_plmm_binary_V`, par, Zt, St, mu, nested, missing_mu)
}

plmm_binary_LL_cpp <- function(par, H, X, Zt, St, mu, nested, REML, verbose) {
    .Call(`_phyr_plmm_binary_LL_cpp`, par, H, X, Zt, St, mu, nested, REML, verbose)
}

pglmm_binary_internal_cpp <- function(X, Y, Zt, St, nested, REML, verbose, n, p, q, maxit, reltol, tol_pql, maxit_pql, optimizer, B_init, ss) {
    .Call(`_phyr_pglmm_binary_internal_cpp`, X, Y, Zt, St, nested, REML, verbose, n, p, q, maxit, reltol, tol_pql, maxit_pql, optimizer, B_init, ss)
}

sexp_type <- function(x) {
    .Call(`_phyr_sexp_type`, x)
}

pglmm_gaussian_LL_cpp <- function(par, X, Y, Zt, St, nested, REML, verbose) {
    .Call(`_phyr_pglmm_gaussian_LL_cpp`, par, X, Y, Zt, St, nested, REML, verbose)
}

pglmm_gaussian_LL_calc_cpp <- function(par, X, Y, Zt, St, nested, REML) {
    .Call(`_phyr_pglmm_gaussian_LL_calc_cpp`, par, X, Y, Zt, St, nested, REML)
}

pglmm_gaussian_internal_cpp <- function(par, X, Y, Zt, St, nested, REML, verbose, optimizer, maxit, reltol, q, n, p, Pi) {
    .Call(`_phyr_pglmm_gaussian_internal_cpp`, par, X, Y, Zt, St, nested, REML, verbose, optimizer, maxit, reltol, q, n, p, Pi)
}

which2 <- function(x) {
    .Call(`_phyr_which2`, x)
}

vcv_loop <- function(xx, n, e1, e2, EL, pp, corr) {
    .Call(`_phyr_vcv_loop`, xx, n, e1, e2, EL, pp, corr)
}

cov2cor_cpp <- function(vcv) {
    invisible(.Call(`_phyr_cov2cor_cpp`, vcv))
}

pse_cpp <- function(comm, Cmatrix) {
    .Call(`_phyr_pse_cpp`, comm, Cmatrix)
}

psv_cpp <- function(comm, Cmatrix, compute_var) {
    .Call(`_phyr_psv_cpp`, comm, Cmatrix, compute_var)
}

