# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pglmm_reml_cpp <- function(par, tinvW, tH, tVphy, tX) {
    .Call(`_phyr_pglmm_reml_cpp`, par, tinvW, tH, tVphy, tX)
}

binpglmm_inter_while_cpp <- function(est_B_m, oldest_B_m, B, tol_pql, iteration_m, maxit_pql, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b) {
    .Call(`_phyr_binpglmm_inter_while_cpp`, est_B_m, oldest_B_m, B, tol_pql, iteration_m, maxit_pql, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b)
}

binpglmm_inter_while_cpp2 <- function(est_B_m, B, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b) {
    .Call(`_phyr_binpglmm_inter_while_cpp2`, est_B_m, B, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b)
}

#' Inner function to create necessary matrices and do model fitting.
#' 
#' @param X a n x p matrix with p columns containing the values for the n taxa.
#' @param U a list of p matrices corresponding to the p columns of X, with each 
#'     matrix containing independent variables for the corresponding column of X.
#' @param SeM a n x p matrix with p columns containing standard errors of the trait 
#'     values in X. 
#' @param Vphy_ 
#' @param REML whether REML or ML is used for model fitting.
#' @param constrain_d if constrain.d is TRUE, the estimates of d are constrained to 
#'     be between zero and 1. This can make estimation more stable and can be 
#'     tried if convergence is problematic. This does not necessarily lead to 
#'     loss of generality of the results, because before using corphylo, branch 
#'     lengths of phy can be transformed so that the "starter" tree has strong 
#'     phylogenetic signal.
#' @param verbose if TRUE, the model logLik and running estimates of the correlation 
#'     coefficients and values of d are printed each iteration during optimization.
#' @param max_iter the maximum number of iterations in the optimization.
#' @param method method of optimization using nlopt. Options include 
#'     "bobyqa", "cobyla", "praxis". See
#'     \url{https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/} for more 
#'     information.
#' 
#' @return List containing output information, to be coerced to a cor_phylo object.
#' 
#' 
cor_phylo_ <- function(X, U, SeM, Vphy_, REML, constrain_d, verbose, max_iter, method) {
    .Call(`_phyr_cor_phylo_`, X, U, SeM, Vphy_, REML, constrain_d, verbose, max_iter, method)
}

set_seed <- function(seed) {
    invisible(.Call(`_phyr_set_seed`, seed))
}

predict_cpp <- function(n, nsr, reps, V) {
    .Call(`_phyr_predict_cpp`, n, nsr, reps, V)
}

pcd2_loop <- function(SSii, nsr, SCii, comm, V, nsp_pool, verbose) {
    .Call(`_phyr_pcd2_loop`, SSii, nsr, SCii, comm, V, nsp_pool, verbose)
}

plmm_binary_iV_logdetV_cpp <- function(par, mu, Zt, St, nested, logdet) {
    .Call(`_phyr_plmm_binary_iV_logdetV_cpp`, par, mu, Zt, St, nested, logdet)
}

plmm_binary_V <- function(par, Zt, St, mu, nested, missing_mu) {
    .Call(`_phyr_plmm_binary_V`, par, Zt, St, mu, nested, missing_mu)
}

plmm_binary_LL_cpp <- function(par, H, X, Zt, St, mu, nested, REML, verbose) {
    .Call(`_phyr_plmm_binary_LL_cpp`, par, H, X, Zt, St, mu, nested, REML, verbose)
}

pglmm_binary_internal_cpp <- function(X, Y, Zt, St, nested, REML, verbose, n, p, q, maxit, reltol, tol_pql, maxit_pql, optimizer, B_init, ss) {
    .Call(`_phyr_pglmm_binary_internal_cpp`, X, Y, Zt, St, nested, REML, verbose, n, p, q, maxit, reltol, tol_pql, maxit_pql, optimizer, B_init, ss)
}

sexp_type <- function(x) {
    .Call(`_phyr_sexp_type`, x)
}

pglmm_gaussian_LL_cpp <- function(par, X, Y, Zt, St, nested, REML, verbose) {
    .Call(`_phyr_pglmm_gaussian_LL_cpp`, par, X, Y, Zt, St, nested, REML, verbose)
}

pglmm_gaussian_LL_calc_cpp <- function(par, X, Y, Zt, St, nested, REML) {
    .Call(`_phyr_pglmm_gaussian_LL_calc_cpp`, par, X, Y, Zt, St, nested, REML)
}

pglmm_gaussian_internal_cpp <- function(par, X, Y, Zt, St, nested, REML, verbose, optimizer, maxit, reltol, q, n, p, Pi) {
    .Call(`_phyr_pglmm_gaussian_internal_cpp`, par, X, Y, Zt, St, nested, REML, verbose, optimizer, maxit, reltol, q, n, p, Pi)
}

