# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pglmm_reml_cpp <- function(par, tinvW, tH, tVphy, tX) {
    .Call(`_phyr_pglmm_reml_cpp`, par, tinvW, tH, tVphy, tX)
}

binpglmm_inter_while_cpp <- function(est_B_m, oldest_B_m, B, tol_pql, iteration_m, maxit_pql, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b) {
    .Call(`_phyr_binpglmm_inter_while_cpp`, est_B_m, oldest_B_m, B, tol_pql, iteration_m, maxit_pql, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b)
}

binpglmm_inter_while_cpp2 <- function(est_B_m, B, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b) {
    .Call(`_phyr_binpglmm_inter_while_cpp2`, est_B_m, B, mu, C, rcondflag, B_init, X, XX, est_B, y, n, b)
}

set_seed <- function(seed) {
    invisible(.Call(`_phyr_set_seed`, seed))
}

predict_cpp <- function(n, nsr, reps, V) {
    .Call(`_phyr_predict_cpp`, n, nsr, reps, V)
}

pcd2_loop <- function(SSii, nsr, SCii, comm, V, nsp_pool, verbose) {
    .Call(`_phyr_pcd2_loop`, SSii, nsr, SCii, comm, V, nsp_pool, verbose)
}

pglmm_gaussian_LL_cpp <- function(par, X, Y, Zt, St, nested, REML, verbose) {
    .Call(`_phyr_pglmm_gaussian_LL_cpp`, par, X, Y, Zt, St, nested, REML, verbose)
}

pglmm_gaussian_LL_calc_cpp <- function(par, X, Y, Zt, St, nested, REML) {
    .Call(`_phyr_pglmm_gaussian_LL_calc_cpp`, par, X, Y, Zt, St, nested, REML)
}

plmm_binary_iV_logdetV_cpp <- function(par, mu, Zt, St, nested, logdet) {
    .Call(`_phyr_plmm_binary_iV_logdetV_cpp`, par, mu, Zt, St, nested, logdet)
}

plmm_binary_V <- function(par, Zt, St, mu, nested, missing_mu) {
    .Call(`_phyr_plmm_binary_V`, par, Zt, St, mu, nested, missing_mu)
}

